server:
  port: 8080

spring:
  application:
    name: spring-boot-webstore

  datasource: # DataSource Configuration
#    url: jdbc:postgresql://localhost:5432/springboot-webstore
    url: jdbc:postgresql://localhost:5433/springboot-webstore
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa: # JPA / Hibernate Properties
    open-in-view: false
    hibernate:
      # ddl-auto: update
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
#    url: jdbc:postgresql://localhost:5432/springboot-webstore
#    user: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/webstore

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.transaction: info

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Job timing
shop:
  payment:
    timeout-minutes: 30